### PR TITLE
Update cmd/stun-nat-behaviour strictly following RFC5780 & RFC4787

### PR DESCRIPTION
**Pull request by bixycler**
#### Description

- Fix typo in attributes of RFC5780
- Add RESPONSE-ORIGIN and other attributes' types in RFC5780
- Expose GetFromAs() & AddToAs() from addr.go
- Add cmd/stun-nat-behaviour parameters: timeout, verbose
- [_removed_] Make the output clearer with 3 levels of verbosity
- Generate new transaction id for each Binding Request
- NAT mapping tests: 2 tests -> 3 tests (add missing Test II)
- Refactor functions & update docs

#### Reference issue
Previous pull request: #33

### CODE REVIEW

**Comment by Sean-Der** [comment]
Amazing work @bixycler, will review now. Sorry for the delay :(

**Comment by Sean-Der** [comment]
@bixycler What do you think of it being verbose by default? Since this is a debugging tool we can split out the info into separate sections.

But less arguments if possible is better IMO

**Comment by bixycler** [comment]
I'm sorry for many force pushes, but they are just to fix many checking failures due to the strict rules.

Finally, the remaining failure is "File is not `goimports`-ed" which is very confusing. Maybe it's complaining about the many spaces inserted to align the code for good looking. I didn't introduced those spaces myself but found them actually there long before (535395da3ef).

Can someone explain why some commits are checked while some are not, and within the checked ones, the check lists are also different.

**Comment by bixycler** [comment]
> Finally, the remaining failure is "File is not `goimports`-ed" which is very confusing. 

With the newer version of `golangci-lint` (1.28.2), I see a clearer message about that error: "File is not `gofmt`-ed with `-s`".

Even though `-s` is about simplifying code but it does align all `var` lists according to its own rule! So, I just re-align them following `gofmt -s` anyway.

**Comment by Sean-Der** [comment]
This is quite an amazing PR, @bixycler easily one of the best 'First PRs' Pion has ever seen!

Would you be interested in joining the pion org? I would love to have your continued involvement in the project :) No real responsibility, but it would be really great to have who knows this stuff much deeper then me!

**Comment by Sean-Der** [comment]
I think I was wrong about removing the verbosity levels. I love all the extra info, but beginners will find it overwhelming. 

I can take this PR, but if you are interested it would be great to bring back the levels. I just got caught up on all the verbose level checking. Maybe if we used the `log` package, and used log levels instead the code would be easier to follow?

**Comment by bixycler** [comment]
> Maybe if we used the `log` package, and used log levels instead the code would be easier to follow?

I don't see the "levels" in Go's standard `log` package. But I'm trying [logrus](https://github.com/sirupsen/logrus) to implements the 3 levels of logging:

0. Only results (mapping & filtering)
1. [Default] The tests being carried out and then results
2. (1) + details in STUN messages (both requests & responses)

> Would you be interested in joining the pion org?

I've joined, haven't I? :open_mouth: ?! I've just changed my Pion's membership from "private" -> "public".

**Pull request merged**
