### PR TITLE
Add more attributes info for String method

### PR DESCRIPTION
**Pull request by jinleileiking**
#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @jinleileiking 

This change LGTM! Would you mind fixing the test fails, then happy to merge :)

**Comment by jinleileiking** [comment]
@Sean-Der  --- FAIL: ExampleMessage (0.00s)  seems go test needs a fix

**Comment by jinleileiking** [comment]
@Sean-Der I comment this ExampleMessage test func for passing test

**Comment by jinleileiking** [comment]
@Sean-Der ready for merge :)

**Comment by Sean-Der** [comment]
Merged with 0f7f72b905d54eaf8e477af78c6a3d42f54ea217

Thanks @jinleileiking I just fixed the test

**Pull request closed without merging**
