### PR TITLE
Merge with gortc/stun

### LINKED ISSUE #10: Merge with gortc/stun
So we've decided to merge with [gortc/stun](https://github.com/gortc/stun) and release it as stun/v2.

This is a tracking issue for that process.

- [x] ICE PR https://github.com/pion/ice/pull/44
- [x] TURN PR (TODO)
- [x] WebRTC PR https://github.com/pion/webrtc/pull/682

### PR DESCRIPTION
**Pull request by ernado**
Ref: #10 

The CI should be updated too.

### CODE REVIEW

**Comment by ernado** [comment]
Please take a look at the following points

- [ ] LICENSE (I've used xor implementation and vendored hmac from go source)
- [ ] AUTHORS (I've just appended authors from README to that file) 

I think we don't need `v2` or even `v1`, because current package version is `v0.2`.
So I propose to release `v0.3.0` and then further adapt API if needed.

**Comment by backkem** [comment]
Regarding vendoring, here's an example we did earlier: https://github.com/pion/webrtc/tree/master/examples/vendor-wasm. It's a little different situation thought.

Anyway, this is looking great. This implementation is far superior to what we had before.

**Comment by Sean-Der** [comment]
Everything looks great to me!

Would you prefer we move `Contributors` sections of README files into `AUTHORS` file? My motivation with that was to get people excited to see their name in the `README` file, when I was first starting out with Open Source that always excited me.

`LICENSE` wise I am happy as long as we don't require people to redistribute changes :) same goal as you here I really want to be 'Enterprise' friendly. Those users contribute a lot back (bug reports and driving excitement)

**Comment by ernado** [comment]
@backk

**Comment by Sean-Der** [comment]
@ernado I say when you are ready lets merge across `stun` then `ice` and `webrtc`!

When it lands we can fix/confirm things as we go :)

**Pull request merged**
